### PR TITLE
Towards wd 1.2

### PR DESCRIPTION
**Pull request by msdemlei**
This PR has three rather unconnected changes that should bring this within WDability: A changelog update, and update to the schema sketch to include the STC tables, and a change to rtent to save typing.

### CODE REVIEW

**Comment by mbtaylor** [comment]
Although the version number of this WD has been bumped to 1.2, there are still references to 1.1 in the text, e.g. in section 9.1 and 9.2 _"TAP Servers implementing the ivo://ivoa.net/std/RegTAP#1.1 data model MUST implement..."_

**Comment by msdemlei** [comment]
On Tue, Feb 08, 2022 at 04:41:28AM -0800, Mark Taylor wrote:
> Although the version number of this WD has been bumped to 1.2,
> there are still references to 1.1 in the text, e.g. in section 9.1
> and 9.2 _"TAP Servers implementing the
> ivo://ivoa.net/std/RegTAP#1.1 data model MUST implement..."_

Indeed.  And I was still talking about VODataService 1.1 in the role
section, where the whole point of the operation is to support 1.2.

Thanks for catching these!  Fixes (where I hope I've caught them all
-- perhaps this should be in a macro...) in commit e14e88a.

**Comment by mbtaylor** [comment]
The `rtent` antics seem to have wiped out the whitespace following use of the macro; see e.g. the formatted PDF of section 8.1.

**Comment by msdemlei** [comment]
On Tue, Feb 08, 2022 at 06:02:14AM -0800, Mark Taylor wrote:
> The `rtent` antics seem to have wiped out the whitespace following
> use of the macro; see e.g. the formatted PDF of section 8.1.

Argl.  I stand corrected on doubting the use of going through a PR
here.

Fixed in commit 08d0f7d.

**Review by mbtaylor — APPROVED** [review]
Text OK.  As before, decisions about whether to include these changes in the next RegTAP version will need input from other potential implementors.

**Pull request merged**
