### PR TITLE
initial import

### PR DESCRIPTION
**Pull request by pdowler**
all content from https://github.com/msdemlei/RegTAP

### CODE REVIEW

**Review by msdemlei — APPROVED** [review]
Looks like the move is complete.

**Comment by molinaro-m** [comment]
I suggest @ivoa-std/registry-admin (or someone else) move @msdemlei to a higher role, to be able to approve PRs in this repo, being the doc editor.

**Comment by Zarquan** [comment]
> I suggest @ivoa-std/registry-admin (or someone else) move @msdemlei to a higher role, to be able to approve PRs in this repo, being the doc editor.

Done

**Comment by tsdower** [comment]
I've added @msdemlei so he should be able to approve PRs, and additionally just gone ahead and approved a couple simple ones that were in the queue.

**Pull request merged**
